[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[phases.build]
cmds = ["mvn clean package -pl notification-service -am -DskipTests -q"]

[start]
cmd = "java -Xmx512m -jar notification-service/target/*.jar"
