[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[phases.build]
cmds = ["mvn clean package -pl heat-processing-service -am -DskipTests -q"]

[start]
cmd = "java -Xmx512m -jar heat-processing-service/target/*.jar"
