[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[phases.build]
cmds = ["mvn clean package -pl weather-ingestion-service -am -DskipTests -q"]

[start]
cmd = "java -Xmx512m -jar weather-ingestion-service/target/*.jar"
